version: "2.2"

services:
  eureka_server:
    build:
      context: "./eureka_server/cloud-discovery-eureka-server"
      dockerfile: "./docker/Dockerfile"
    volumes:
      - ./eureka_server/cloud-discovery-eureka-server
    ports:
      - "${BUSINESS_FRONT_PORT:-8761}:8761"
    container_name: eureka_server

