version: "2.2"

services:
  eureka_server:
    privileged: true
    networks:
      msa_network:
        ipv4_address: 172.24.0.2

    build:
      context: "./eureka_server/cloud-discovery-eureka-server"
      dockerfile: "./docker/Dockerfile"
    volumes:
      - ./eureka_server/cloud-discovery-eureka-server:/home/eureka_server
    ports:
      - "${EUREKA_PORT:-8761}:8761"
    container_name: eureka_server
  api_gateway:
    depends_on:
      - "eureka_server"
    networks:
      - msa_network
    build:
      context: "./api-gateway/apigate-service"
      dockerfile: "./docker/Dockerfile"
    volumes:
      - ./api-gateway/apigate-service:/home/api_gateway
    ports:
      - "${API_GATE_PORT:-8000}:8000"
    container_name: api_gateway
    restart: "unless-stopped"
    stop_grace_period: "50s"
#  spring_kafka:
#    depends_on:
#      - "api_gateway"
#    build:
#      context: "./springKafka"
#      dockerfile: "./docker/Dockerfile"
#    networks:
#      - msa_network
#    volumes:
#      - ./springKafka:/home/springKafka
#    ports:
#      - "${KAFKA_PORT:-8080}:8080"
#  user_service:
#    depends_on:
#      - "spring_kafka"
#    build:
#      context: "./user-service"
#      dockerfile: "./docker/Dockerfile"
#    networks:
#      - msa_network
#    volumes:
#      - ./user-service:/home/user-service
#    ports:
#      - "${USER_PORT:-8082}:8082"
networks:
  msa_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
volumes:
  api_gateway:
  eureka_server:

