server:
  port: 8761

spring:
  application:
    name: msa-discovery
  cloud:
    uri: http://127.0.0.1:8888
    name: msa

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
