FROM nginx:1.20
MAINTAINER EDDY KIM <eddy@teamo2.kr>

EXPOSE 8081

#COPY ./nginx.conf /etc/nginx/nginx.conf
#COPY ./default.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]