server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-52-79-122-133.ap-northeast-2.compute.amazonaws.com:8761/eureka


spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gate way Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            #            - AddRequestHeader=second-request, second-request-header2
            #            - AddResponseHeader=second-Response, second-Response-header2
            - name: CustomFilter
            - name: LoggerFilter
              args:
                baseMessage: Hi, I'm Logger filter
                preLogger: true
                postLogger: true
        - id: booker-service
          uri: lb://BOOKER-SERVICE
          predicates:
            - Path=/booker/**
          filters:
            #            - AddRequestHeader=first-request, first-request-header2
            #            - AddResponseHeader=first-Response, first-Response-header2
            - CustomFilter
